// <auto-generated />
using System;
using ExpenseTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910201630_AddReceiptsAndExpenses")]
    partial class AddReceiptsAndExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Dining"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Household"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Transportation"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Health"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StoreId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreName")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            CategoryId = 1,
                            StoreName = "Sobeys"
                        },
                        new
                        {
                            StoreId = 2,
                            CategoryId = 1,
                            StoreName = "Atlantic Superstore"
                        },
                        new
                        {
                            StoreId = 3,
                            CategoryId = 2,
                            StoreName = "Tim Hortons"
                        },
                        new
                        {
                            StoreId = 4,
                            CategoryId = 2,
                            StoreName = "McDonald's"
                        },
                        new
                        {
                            StoreId = 5,
                            CategoryId = 3,
                            StoreName = "Canadian Tire"
                        },
                        new
                        {
                            StoreId = 6,
                            CategoryId = 3,
                            StoreName = "Dollarama"
                        },
                        new
                        {
                            StoreId = 7,
                            CategoryId = 4,
                            StoreName = "Winners"
                        },
                        new
                        {
                            StoreId = 8,
                            CategoryId = 4,
                            StoreName = "Mark's"
                        },
                        new
                        {
                            StoreId = 9,
                            CategoryId = 5,
                            StoreName = "Best Buy"
                        },
                        new
                        {
                            StoreId = 10,
                            CategoryId = 5,
                            StoreName = "Staples"
                        },
                        new
                        {
                            StoreId = 11,
                            CategoryId = 6,
                            StoreName = "Irving"
                        },
                        new
                        {
                            StoreId = 12,
                            CategoryId = 6,
                            StoreName = "Circle K"
                        },
                        new
                        {
                            StoreId = 13,
                            CategoryId = 7,
                            StoreName = "Shoppers Drug Mart"
                        },
                        new
                        {
                            StoreId = 14,
                            CategoryId = 7,
                            StoreName = "Lawtons Drugs"
                        },
                        new
                        {
                            StoreId = 15,
                            CategoryId = 8,
                            StoreName = "Amazon"
                        },
                        new
                        {
                            StoreId = 16,
                            CategoryId = 8,
                            StoreName = "Other"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Expense", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Api.Models.Receipt", "Receipt")
                        .WithMany("Expenses")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Receipt", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Store", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Receipt", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
